### ISSUE TITLE
[Minor Issue] init-pull doesn't create a .upback.config file

### ISSUE THREAD

**Issue by h82k** [DavideRossi/upback#1]
Hello,
I've encountered a minor issue: When initializing a new sync target with `init-pull` the necessary `.upback.config` isn't created. Therefore after the initial sync the execution of upback returns
> The current directory does not belong to an UpBack backup

Tested with a WebDav target on a Windows machine in different directories. `init-push` works without problems. Afterwards `init-pull` is usable as the config is synced.
I suggest adding this to the readme if it is reproducable.

Anyway I want to thank you very much for this excellent software, I can't imagine a 2way sync any more user-friendly.

**Comment by DavideRossi** [comment]
It should be fixed now, I also added a test case
